sudo: required
dist: trusty
language: erlang

services:
  - docker

before_install:
- wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb && sudo dpkg -i erlang-solutions_1.0_all.deb
- sudo apt-get update
- sudo apt-get install -y esl-erlang
- sudo apt-get install -y elixir
- docker run -d --name=s3rver -p 127.0.0.1:4568:4568 -t triplew/s3rver

script:
  - which elixir
  - echo $PATH
  - ls -la /usr/local/bin/elixir
  - ls -la ../lib/elixir/bin/elixir
  - ls -la /usr/local/lib/elixir
  - export PATH=/usr/local/bin:$PATH
  - export ERL_LIBS=/usr/local/lib/elixir/lib 
  - mix local.hex --force
  - mix test

addons:
  hosts:
    - fuga.localhost

