language: elixir
elixir:
    - 1.2.1
otp_release:
    - 18.0

services:
  - docker

sudo: false

before_install:
  - docker run -d --name=s3rver -p 127.0.0.1:4568 -t triplew/s3rver

addons:
  hosts:
    - fuga.localhost

script:
    - mix test
