language: elixir
elixir:
  - 1.2.2
otp_release:
  - 18.2.1
sudo: true

services:
  - docker
before_install:
  - docker run -d --name=s3rver -p 127.0.0.1:4568:4568 -t triplew/s3rver

script:
  - mix test

