services:
  - docker

sudo: false

language: elixir
elixir:
  - 1.2.2
otp_release:
  - 18.0

before_install:
  - docker run -d --name=s3rver -p 127.0.0.1:4568:4568 -t triplew/s3rver

script:
  - mix test

addons:
  hosts:
    - fuga.localhost
